# Fake database to store regions, states, and LGAs
# db = {
#     "regions": [
#         {"id": 1, "name": "North"},
#         {"id": 2, "name": "South"},
#         {"id": 3, "name": "East"},
#         {"id": 4, "name": "West"}
#     ],
#     "states": [
#         {"id": 1, "name": "Lagos", "region_id": 4},
#         {"id": 2, "name": "Kano", "region_id": 1},
#         {"id": 3, "name": "Rivers", "region_id": 2}
#         # Add more states
#     ],
#     "lgas": [
#         {"id": 1, "name": "Ikeja", "state_id": 1},
#         {"id": 2, "name": "Agege", "state_id": 1},
#         {"id": 3, "name": "Kano Municipal", "state_id": 2},
#         {"id": 4, "name": "Nassarawa", "state_id": 2},
#         {"id": 5, "name": "Port Harcourt", "state_id": 3},
#         {"id": 6, "name": "Obio-Akpor", "state_id": 3}
#         # Add more LGAs
#     ]
# }

# Fake database to store API keys
api_keys_db = {}



db = {
    "regions": [
        {"id": 1, "name": "North Central"},
        {"id": 2, "name": "North East"},
        {"id": 3, "name": "North West"},
        {"id": 4, "name": "South East"},
        {"id": 5, "name": "South South"},
        {"id": 6, "name": "South West"}
    ],
    "states": [
        {"id": 1, "name": "Abia", "region_id": 4},
        {"id": 2, "name": "Adamawa", "region_id": 2},
        {"id": 3, "name": "Akwa Ibom", "region_id": 5},
        {"id": 4, "name": "Anambra", "region_id": 4},
        {"id": 5, "name": "Bauchi", "region_id": 2},
        {"id": 6, "name": "Bayelsa", "region_id": 5},
        {"id": 7, "name": "Benue", "region_id": 1},
        {"id": 8, "name": "Borno", "region_id": 2},
        {"id": 9, "name": "Cross River", "region_id": 5},
        {"id": 10, "name": "Delta", "region_id": 5},
        {"id": 11, "name": "Ebonyi", "region_id": 4},
        {"id": 12, "name": "Edo", "region_id": 5},
        {"id": 13, "name": "Ekiti", "region_id": 6},
        {"id": 14, "name": "Enugu", "region_id": 4},
        {"id": 15, "name": "FCT", "region_id": 1},
        {"id": 16, "name": "Gombe", "region_id": 2},
        {"id": 17, "name": "Imo", "region_id": 4},
        {"id": 18, "name": "Jigawa", "region_id": 3},
        {"id": 19, "name": "Kaduna", "region_id": 3},
        {"id": 20, "name": "Kano", "region_id": 3},
        {"id": 21, "name": "Katsina", "region_id": 3},
        {"id": 22, "name": "Kebbi", "region_id": 3},
        {"id": 23, "name": "Kogi", "region_id": 1},
        {"id": 24, "name": "Kwara", "region_id": 1},
        {"id": 25, "name": "Lagos", "region_id": 6},
        {"id": 26, "name": "Nasarawa", "region_id": 1},
        {"id": 27, "name": "Niger", "region_id": 1},
        {"id": 28, "name": "Ogun", "region_id": 6},
        {"id": 29, "name": "Ondo", "region_id": 6},
        {"id": 30, "name": "Osun", "region_id": 6},
        {"id": 31, "name": "Oyo", "region_id": 6},
        {"id": 32, "name": "Plateau", "region_id": 1},
        {"id": 33, "name": "Rivers", "region_id": 5},
        {"id": 34, "name": "Sokoto", "region_id": 3},
        {"id": 35, "name": "Taraba", "region_id": 2},
        {"id": 36, "name": "Yobe", "region_id": 2},
        {"id": 37, "name": "Zamfara", "region_id": 3}
    ],
    "lgas": [
        # LGAs for Abia State
        {"id": 1, "name": "Aba North", "state_id": 1},
        {"id": 2, "name": "Aba South", "state_id": 1},
        {"id": 3, "name": "Arochukwu", "state_id": 1},
        {"id": 4, "name": "Bende", "state_id": 1},
        {"id": 5, "name": "Ikwuano", "state_id": 1},
        {"id": 6, "name": "Isiala Ngwa North", "state_id": 1},
        {"id": 7, "name": "Isiala Ngwa South", "state_id": 1},
        {"id": 8, "name": "Isuikwuato", "state_id": 1},
        {"id": 9, "name": "Obi Ngwa", "state_id": 1},
        {"id": 10, "name": "Ohafia", "state_id": 1},
        {"id": 11, "name": "Osisioma", "state_id": 1},
        {"id": 12, "name": "Ugwunagbo", "state_id": 1},
        {"id": 13, "name": "Ukwa East", "state_id": 1},
        {"id": 14, "name": "Ukwa West", "state_id": 1},
        {"id": 15, "name": "Umuahia North", "state_id": 1},
        {"id": 16, "name": "Umuahia South", "state_id": 1},
        {"id": 17, "name": "Umu Nneochi", "state_id": 1},
        # LGAs for Adamawa State
        {"id": 18, "name": "Demsa", "state_id": 2},
        {"id": 19, "name": "Fufore", "state_id": 2},
        {"id": 20, "name": "Ganye", "state_id": 2},
        {"id": 21, "name": "Girei", "state_id": 2},
        {"id": 22, "name": "Gombi", "state_id": 2},
        {"id": 23, "name": "Guyuk", "state_id": 2},
        {"id": 24, "name": "Hong", "state_id": 2},
        {"id": 25, "name": "Jada", "state_id": 2},
        {"id": 26, "name": "Lamurde", "state_id": 2},
        {"id": 27, "name": "Madagali", "state_id": 2},
        {"id": 28, "name": "Maiha", "state_id": 2},
        {"id": 29, "name": "Mayo Belwa", "state_id": 2},
        {"id": 30, "name": "Michika", "state_id": 2},
        {"id": 31, "name": "Mubi North", "state_id": 2},
        {"id": 32, "name": "Mubi South", "state_id": 2},
        {"id": 33, "name": "Numan", "state_id": 2},
        {"id": 34, "name": "Shelleng", "state_id": 2},
        {"id": 35, "name": "Song", "state_id": 2},
        {"id": 36, "name": "Toungo", "state_id": 2},
        {"id": 37, "name": "Yola North", "state_id": 2},
        {"id": 38, "name": "Yola South", "state_id": 2},
        # LGAs for Akwa Ibom State
        {"id": 39, "name": "Abak", "state_id": 3},
        {"id": 40, "name": "Eastern Obolo", "state_id": 3},
        {"id": 41, "name": "Eket", "state_id": 3},
        {"id": 42, "name": "Esit Eket", "state_id": 3},
        {"id": 43, "name": "Essien Udim", "state_id": 3},
        {"id": 44, "name": "Etim Ekpo", "state_id": 3},
        {"id": 45, "name": "Etinan", "state_id": 3},
        {"id": 46, "name": "Ibeno", "state_id": 3},
        {"id": 47, "name": "Ibesikpo Asutan", "state_id": 3},
        {"id": 48, "name": "Ibiono Ibom", "state_id": 3},
        {"id": 49, "name": "Ika", "state_id": 3},
        {"id": 50, "name": "Ikono", "state_id": 3},
        {"id": 51, "name": "Ikot Abasi", "state_id": 3},
        {"id": 52, "name": "Ikot Ekpene", "state_id": 3},
        {"id": 53, "name": "Ini", "state_id": 3},
        {"id": 54, "name": "Itu", "state_id": 3},
        {"id": 55, "name": "Mbo", "state_id": 3},
        {"id": 56, "name": "Mkpat Enin", "state_id": 3},
        {"id": 57, "name": "Nsit Atai", "state_id": 3},
        {"id": 58, "name": "Nsit Ibom", "state_id": 3},
        {"id": 59, "name": "Nsit Ubium", "state_id": 3},
        {"id": 60, "name": "Obot Akara", "state_id": 3},
        {"id": 61, "name": "Okobo", "state_id": 3},
        {"id": 62, "name": "Onna", "state_id": 3},
        {"id": 63, "name": "Oron", "state_id": 3},
        {"id": 64, "name": "Oruk Anam", "state_id": 3},
        {"id": 65, "name": "Udung Uko", "state_id": 3},
        {"id": 66, "name": "Ukanafun", "state_id": 3},
        {"id": 67, "name": "Uruan", "state_id": 3},
        {"id": 68, "name": "Urue-Offong/Oruko", "state_id": 3},
        {"id": 69, "name": "Uyo", "state_id": 3},
        # LGAs for Anambra State
        {"id": 70, "name": "Aguata", "state_id": 4},
        {"id": 71, "name": "Anambra East", "state_id": 4},
        {"id": 72, "name": "Anambra West", "state_id": 4},
        {"id": 73, "name": "Anaocha", "state_id": 4},
        {"id": 74, "name": "Awka North", "state_id": 4},
        {"id": 75, "name": "Awka South", "state_id": 4},
        {"id": 76, "name": "Ayamelum", "state_id": 4},
        {"id": 77, "name": "Dunukofia", "state_id": 4},
        {"id": 78, "name": "Ekwusigo", "state_id": 4},
        {"id": 79, "name": "Idemili North", "state_id": 4},
        {"id": 80, "name": "Idemili South", "state_id": 4},
        {"id": 81, "name": "Ihiala", "state_id": 4},
        {"id": 82, "name": "Njikoka", "state_id": 4},
        {"id": 83, "name": "Nnewi North", "state_id": 4},
        {"id": 84, "name": "Nnewi South", "state_id": 4},
        {"id": 85, "name": "Ogbaru", "state_id": 4},
        {"id": 86, "name": "Onitsha North", "state_id": 4},
        {"id": 87, "name": "Onitsha South", "state_id": 4},
        {"id": 88, "name": "Orumba North", "state_id": 4},
        {"id": 89, "name": "Orumba South", "state_id": 4},
        {"id": 90, "name": "Oyi", "state_id": 4},
        # LGAs for Bauchi State
        {"id": 91, "name": "Alkaleri", "state_id": 5},
        {"id": 92, "name": "Bauchi", "state_id": 5},
        {"id": 93, "name": "Bogoro", "state_id": 5},
        {"id": 94, "name": "Damban", "state_id": 5},
        {"id": 95, "name": "Darazo", "state_id": 5},
        {"id": 96, "name": "Dass", "state_id": 5},
        {"id": 97, "name": "Gamawa", "state_id": 5},
        {"id": 98, "name": "Ganjuwa", "state_id": 5},
        {"id": 99, "name": "Giade", "state_id": 5},
        {"id": 100, "name": "Itas/Gadau", "state_id": 5},
        {"id": 101, "name": "Jama'are", "state_id": 5},
        {"id": 102, "name": "Katagum", "state_id": 5},
        {"id": 103, "name": "Kirfi", "state_id": 5},
        {"id": 104, "name": "Misau", "state_id": 5},
        {"id": 105, "name": "Ningi", "state_id": 5},
        {"id": 106, "name": "Shira", "state_id": 5},
        {"id": 107, "name": "Tafawa Balewa", "state_id": 5},
        {"id": 108, "name": "Toro", "state_id": 5},
        {"id": 109, "name": "Warji", "state_id": 5},
        {"id": 110, "name": "Zaki", "state_id": 5},
        # LGAs for Bayelsa State
        {"id": 111, "name": "Brass", "state_id": 6},
        {"id": 112, "name": "Ekeremor", "state_id": 6},
        {"id": 113, "name": "Kolokuma/Opokuma", "state_id": 6},
        {"id": 114, "name": "Nembe", "state_id": 6},
        {"id": 115, "name": "Ogbia", "state_id": 6},
        {"id": 116, "name": "Sagbama", "state_id": 6},
        {"id": 117, "name": "Southern Ijaw", "state_id": 6},
        {"id": 118, "name": "Yenagoa", "state_id": 6},
        # LGAs for Benue State
        {"id": 119, "name": "Ado", "state_id": 7},
        {"id": 120, "name": "Agatu", "state_id": 7},
        {"id": 121, "name": "Apa", "state_id": 7},
        {"id": 122, "name": "Buruku", "state_id": 7},
        {"id": 123, "name": "Gboko", "state_id": 7},
        {"id": 124, "name": "Guma", "state_id": 7},
        {"id": 125, "name": "Gwer East", "state_id": 7},
        {"id": 126, "name": "Gwer West", "state_id": 7},
        {"id": 127, "name": "Katsina-Ala", "state_id": 7},
        {"id": 128, "name": "Konshisha", "state_id": 7},
        {"id": 129, "name": "Kwande", "state_id": 7},
        {"id": 130, "name": "Logo", "state_id": 7},
        {"id": 131, "name": "Makurdi", "state_id": 7},
        {"id": 132, "name": "Obi", "state_id": 7},
        {"id": 133, "name": "Ogbadibo", "state_id": 7},
        {"id": 134, "name": "Ohimini", "state_id": 7},
        {"id": 135, "name": "Oju", "state_id": 7},
        {"id": 136, "name": "Okpokwu", "state_id": 7},
        {"id": 137, "name": "Oturkpo", "state_id": 7},
        {"id": 138, "name": "Tarka", "state_id": 7},
        {"id": 139, "name": "Ukum", "state_id": 7},
        {"id": 140, "name": "Ushongo", "state_id": 7},
        {"id": 141, "name": "Vandeikya", "state_id": 7},
        # LGAs for Borno State
        {"id": 142, "name": "Abadam", "state_id": 8},
        {"id": 143, "name": "Askira/Uba", "state_id": 8},
        {"id": 144, "name": "Bama", "state_id": 8},
        {"id": 145, "name": "Bayo", "state_id": 8},
        {"id": 146, "name": "Biu", "state_id": 8},
        {"id": 147, "name": "Chibok", "state_id": 8},
        {"id": 148, "name": "Damboa", "state_id": 8},
        {"id": 149, "name": "Dikwa", "state_id": 8},
        {"id": 150, "name": "Gubio", "state_id": 8},
        {"id": 151, "name": "Guzamala", "state_id": 8},
        {"id": 152, "name": "Gwoza", "state_id": 8},
        {"id": 153, "name": "Hawul", "state_id": 8},
        {"id": 154, "name": "Jere", "state_id": 8},
        {"id": 155, "name": "Kaga", "state_id": 8},
        {"id": 156, "name": "Kala/Balge", "state_id": 8},
        {"id": 157, "name": "Konduga", "state_id": 8},
        {"id": 158, "name": "Kukawa", "state_id": 8},
        {"id": 159, "name": "Kwaya Kusar", "state_id": 8},
        {"id": 160, "name": "Mafa", "state_id": 8},
        {"id": 161, "name": "Magumeri", "state_id": 8},
        {"id": 162, "name": "Maiduguri", "state_id": 8},
        {"id": 163, "name": "Marte", "state_id": 8},
        {"id": 164, "name": "Mobbar", "state_id": 8},
        {"id": 165, "name": "Monguno", "state_id": 8},
        {"id": 166, "name": "Ngala", "state_id": 8},
        {"id": 167, "name": "Nganzai", "state_id": 8},
        {"id": 168, "name": "Shani", "state_id": 8},
        # LGAs for Cross River State
        {"id": 169, "name": "Akpabuyo", "state_id": 9},
        {"id": 170, "name": "Akpamkpa", "state_id": 9},
        {"id": 171, "name": "Bakassi", "state_id": 9},
        {"id": 172, "name": "Bekwarra", "state_id": 9},
        {"id": 173, "name": "Biase", "state_id": 9},
        {"id": 174, "name": "Boki", "state_id": 9},
        {"id": 175, "name": "Calabar Municipal", "state_id": 9},
        {"id": 176, "name": "Calabar South", "state_id": 9},
        {"id": 177, "name": "Etung", "state_id": 9},
        {"id": 178, "name": "Ikom", "state_id": 9},
        {"id": 179, "name": "Obanliku", "state_id": 9},
        {"id": 180, "name": "Obubra", "state_id": 9},
        {"id": 181, "name": "Obudu", "state_id": 9},
        {"id": 182, "name": "Odukpani", "state_id": 9},
        {"id": 183, "name": "Ogoja", "state_id": 9},
        {"id": 184, "name": "Yakuur", "state_id": 9},
        {"id": 185, "name": "Yala", "state_id": 9},
        # LGAs for Delta State
        {"id": 186, "name": "Aniocha North", "state_id": 10},
        {"id": 187, "name": "Aniocha South", "state_id": 10},
        {"id": 188, "name": "Bomadi", "state_id": 10},
        {"id": 189, "name": "Burutu", "state_id": 10},
        {"id": 190, "name": "Ethiope East", "state_id": 10},
        {"id": 191, "name": "Ethiope West", "state_id": 10},
        {"id": 192, "name": "Ika North East", "state_id": 10},
        {"id": 193, "name": "Ika South", "state_id": 10},
        {"id": 194, "name": "Isoko North", "state_id": 10},
        {"id": 195, "name": "Isoko South", "state_id": 10},
        {"id": 196, "name": "Ndokwa East", "state_id": 10},
        {"id": 197, "name": "Ndokwa West", "state_id": 10},
        {"id": 198, "name": "Okpe", "state_id": 10},
        {"id": 199, "name": "Oshimili North", "state_id": 10},
        {"id": 200, "name": "Oshimili South", "state_id": 10},
        {"id": 201, "name": "Patani", "state_id": 10},
        {"id": 202, "name": "Sapele", "state_id": 10},
        {"id": 203, "name": "Udu", "state_id": 10},
        {"id": 204, "name": "Ughelli North", "state_id": 10},
        {"id": 205, "name": "Ughelli South", "state_id": 10},
        {"id": 206, "name": "Ukwuani", "state_id": 10},
        {"id": 207, "name": "Uvwie", "state_id": 10},
        {"id": 208, "name": "Warri North", "state_id": 10},
        {"id": 209, "name": "Warri South", "state_id": 10},
        {"id": 210, "name": "Warri South West", "state_id": 10},
        # LGAs for Ebonyi State
        {"id": 211, "name": "Abakaliki", "state_id": 11},
        {"id": 212, "name": "Afikpo North", "state_id": 11},
        {"id": 213, "name": "Afikpo South", "state_id": 11},
        {"id": 214, "name": "Ebonyi", "state_id": 11},
        {"id": 215, "name": "Ezza North", "state_id": 11},
        {"id": 216, "name": "Ezza South", "state_id": 11},
        {"id": 217, "name": "Ikwo", "state_id": 11},
        {"id": 218, "name": "Ishielu", "state_id": 11},
        {"id": 219, "name": "Ivo", "state_id": 11},
        {"id": 220, "name": "Izzi", "state_id": 11},
        {"id": 221, "name": "Ohaozara", "state_id": 11},
        {"id": 222, "name": "Ohaukwu", "state_id": 11},
        {"id": 223, "name": "Onicha", "state_id": 11},
        # LGAs for Edo State
        {"id": 224, "name": "Akoko-Edo", "state_id": 12},
        {"id": 225, "name": "Egor", "state_id": 12},
        {"id": 226, "name": "Esan Central", "state_id": 12},
        {"id": 227, "name": "Esan North-East", "state_id": 12},
        {"id": 228, "name": "Esan South-East", "state_id": 12},
        {"id": 229, "name": "Esan West", "state_id": 12},
        {"id": 230, "name": "Etsako Central", "state_id": 12},
        {"id": 231, "name": "Etsako East", "state_id": 12},
        {"id": 232, "name": "Etsako West", "state_id": 12},
        {"id": 233, "name": "Igueben", "state_id": 12},
        {"id": 234, "name": "Ikpoba Okha", "state_id": 12},
        {"id": 235, "name": "Orhionmwon", "state_id": 12},
        {"id": 236, "name": "Oredo", "state_id": 12},
        {"id": 237, "name": "Ovia North-East", "state_id": 12},
        {"id": 238, "name": "Ovia South-West", "state_id": 12},
        {"id": 239, "name": "Owan East", "state_id": 12},
        {"id": 240, "name": "Owan West", "state_id": 12},
        {"id": 241, "name": "Uhunmwonde", "state_id": 12},
        # LGAs for Ekiti State
        {"id": 242, "name": "Ado Ekiti", "state_id": 13},
        {"id": 243, "name": "Efon", "state_id": 13},
        {"id": 244, "name": "Ekiti East", "state_id": 13},
        {"id": 245, "name": "Ekiti South-West", "state_id": 13},
        {"id": 246, "name": "Ekiti West", "state_id": 13},
        {"id": 247, "name": "Emure", "state_id": 13},
        {"id": 248, "name": "Gbonyin", "state_id": 13},
        {"id": 249, "name": "Ido Osi", "state_id": 13},
        {"id": 250, "name": "Ijero", "state_id": 13},
        {"id": 251, "name": "Ikere", "state_id": 13},
        {"id": 252, "name": "Ikole", "state_id": 13},
        {"id": 253, "name": "Ilejemeje", "state_id": 13},
        {"id": 254, "name": "Irepodun/Ifelodun", "state_id": 13},
        {"id": 255, "name": "Ise/Orun", "state_id": 13},
        {"id": 256, "name": "Moba", "state_id": 13},
        {"id": 257, "name": "Oye", "state_id": 13},
        # LGAs for Enugu State
        {"id": 258, "name": "Aninri", "state_id": 14},
        {"id": 259, "name": "Awgu", "state_id": 14},
        {"id": 260, "name": "Enugu East", "state_id": 14},
        {"id": 261, "name": "Enugu North", "state_id": 14},
        {"id": 262, "name": "Enugu South", "state_id": 14},
        {"id": 263, "name": "Ezeagu", "state_id": 14},
        {"id": 264, "name": "Igbo Etiti", "state_id": 14},
        {"id": 265, "name": "Igbo Eze North", "state_id": 14},
        {"id": 266, "name": "Igbo Eze South", "state_id": 14},
        {"id": 267, "name": "Isi Uzo", "state_id": 14},
        {"id": 268, "name": "Nkanu East", "state_id": 14},
        {"id": 269, "name": "Nkanu West", "state_id": 14},
        {"id": 270, "name": "Nsukka", "state_id": 14},
        {"id": 271, "name": "Oji River", "state_id": 14},
        {"id": 272, "name": "Udenu", "state_id": 14},
        {"id": 273, "name": "Udi", "state_id": 14},
        {"id": 274, "name": "Uzo Uwani", "state_id": 14},
        # LGAs for Gombe State
        {"id": 277, "name": "Akko", "state_id": 15},
        {"id": 278, "name": "Balanga", "state_id": 15},
        {"id": 279, "name": "Billiri", "state_id": 15},
        {"id": 280, "name": "Dukku", "state_id": 15},
        {"id": 281, "name": "Funakaye", "state_id": 15},
        {"id": 282, "name": "Gombe", "state_id": 15},
        {"id": 283, "name": "Kaltungo", "state_id": 15},
        {"id": 284, "name": "Kwami", "state_id": 15},
        {"id": 285, "name": "Nafada", "state_id": 15},
        {"id": 286, "name": "Shongom", "state_id": 15},
        {"id": 287, "name": "Yamaltu/Deba", "state_id": 15},
        # LGAs for Imo State
        {"id": 288, "name": "Aboh Mbaise", "state_id": 16},
        {"id": 289, "name": "Ahiazu Mbaise", "state_id": 16},
        {"id": 290, "name": "Ehime Mbano", "state_id": 16},
        {"id": 291, "name": "Ezinihitte", "state_id": 16},
        {"id": 292, "name": "Ideato North", "state_id": 16},
        {"id": 293, "name": "Ideato South", "state_id": 16},
        {"id": 294, "name": "Ihitte/Uboma", "state_id": 16},
        {"id": 295, "name": "Ikeduru", "state_id": 16},
        {"id": 296, "name": "Isiala Mbano", "state_id": 16},
        {"id": 297, "name": "Isu", "state_id": 16},
        {"id": 298, "name": "Mbaitoli", "state_id": 16},
        {"id": 299, "name": "Ngor Okpala", "state_id": 16},
        {"id": 300, "name": "Njaba", "state_id": 16},
        {"id": 301, "name": "Nkwerre", "state_id": 16},
        {"id": 302, "name": "Nwangele", "state_id": 16},
        {"id": 303, "name": "Obowo", "state_id": 16},
        {"id": 304, "name": "Oguta", "state_id": 16},
        {"id": 305, "name": "Ohaji/Egbema", "state_id": 16},
        {"id": 306, "name": "Okigwe", "state_id": 16},
        {"id": 307, "name": "Orlu", "state_id": 16},
        {"id": 308, "name": "Orsu", "state_id": 16},
        {"id": 309, "name": "Oru East", "state_id": 16},
        {"id": 310, "name": "Oru West", "state_id": 16},
        {"id": 311, "name": "Owerri Municipal", "state_id": 16},
        {"id": 312, "name": "Owerri North", "state_id": 16},
        {"id": 313, "name": "Owerri West", "state_id": 16},
        # LGAs for Jigawa State
        {"id": 314, "name": "Auyo", "state_id": 17},
        {"id": 315, "name": "Babura", "state_id": 17},
        {"id": 316, "name": "Biriniwa", "state_id": 17},
        {"id": 317, "name": "Birnin Kudu", "state_id": 17},
        {"id": 318, "name": "Buji", "state_id": 17},
        {"id": 319, "name": "Dutse", "state_id": 17},
        {"id": 320, "name": "Gagarawa", "state_id": 17},
        {"id": 321, "name": "Garki", "state_id": 17},
        {"id": 322, "name": "Gumel", "state_id": 17},
        {"id": 323, "name": "Guri", "state_id": 17},
        {"id": 324, "name": "Gwaram", "state_id": 17},
        {"id": 325, "name": "Gwiwa", "state_id": 17},
        {"id": 326, "name": "Hadejia", "state_id": 17},
        {"id": 327, "name": "Jahun", "state_id": 17},
        {"id": 328, "name": "Kafin Hausa", "state_id": 17},
        {"id": 329, "name": "Kaugama", "state_id": 17},
        {"id": 330, "name": "Kazaure", "state_id": 17},
        {"id": 331, "name": "Kiri Kasama", "state_id": 17},
        {"id": 332, "name": "Kiyawa", "state_id": 17},
        {"id": 333, "name": "Maigatari", "state_id": 17},
        {"id": 334, "name": "Malam Madori", "state_id": 17},
        {"id": 335, "name": "Miga", "state_id": 17},
        {"id": 336, "name": "Ringim", "state_id": 17},
        {"id": 337, "name": "Roni", "state_id": 17},
        {"id": 338, "name": "Sule Tankarkar", "state_id": 17},
        {"id": 339, "name": "Taura", "state_id": 17},
        {"id": 340, "name": "Yankwashi", "state_id": 17},
        # LGAs for Kaduna State
        {"id": 341, "name": "Birnin Gwari", "state_id": 18},
        {"id": 342, "name": "Chikun", "state_id": 18},
        {"id": 343, "name": "Giwa", "state_id": 18},
        {"id": 344, "name": "Igabi", "state_id": 18},
        {"id": 345, "name": "Ikara", "state_id": 18},
        {"id": 346, "name": "Jaba", "state_id": 18},
        {"id": 347, "name": "Jema'a", "state_id": 18},
        {"id": 348, "name": "Kachia", "state_id": 18},
        {"id": 349, "name": "Kaduna North", "state_id": 18},
        {"id": 350, "name": "Kaduna South", "state_id": 18},
        {"id": 351, "name": "Kagarko", "state_id": 18},
        {"id": 352, "name": "Kajuru", "state_id": 18},
        {"id": 353, "name": "Kaura", "state_id": 18},
        {"id": 354, "name": "Kauru", "state_id": 18},
        {"id": 355, "name": "Kubau", "state_id": 18},
        {"id": 356, "name": "Kudan", "state_id": 18},
        {"id": 357, "name": "Lere", "state_id": 18},
        {"id": 358, "name": "Makarfi", "state_id": 18},
        {"id": 359, "name": "Sabon Gari", "state_id": 18},
        {"id": 360, "name": "Sanga", "state_id": 18},
        {"id": 361, "name": "Soba", "state_id": 18},
        {"id": 362, "name": "Zangon Kataf", "state_id": 18},
        {"id": 363, "name": "Zaria", "state_id": 18},
        # LGAs for Kano State
        {"id": 364, "name": "Ajingi", "state_id": 19},
        {"id": 365, "name": "Albasu", "state_id": 19},
        {"id": 366, "name": "Bagwai", "state_id": 19},
        {"id": 367, "name": "Bebeji", "state_id": 19},
        {"id": 368, "name": "Bichi", "state_id": 19},
        {"id": 369, "name": "Bunkure", "state_id": 19},
        {"id": 370, "name": "Dala", "state_id": 19},
        {"id": 371, "name": "Dambatta", "state_id": 19},
        {"id": 372, "name": "Dawakin Kudu", "state_id": 19},
        {"id": 373, "name": "Dawakin Tofa", "state_id": 19},
        {"id": 374, "name": "Doguwa", "state_id": 19},
        {"id": 375, "name": "Fagge", "state_id": 19},
        {"id": 376, "name": "Gabasawa", "state_id": 19},
        {"id": 377, "name": "Garko", "state_id": 19},
        {"id": 378, "name": "Garun Mallam", "state_id": 19},
        {"id": 379, "name": "Gaya", "state_id": 19},
        {"id": 380, "name": "Gezawa", "state_id": 19},
        {"id": 381, "name": "Gwale", "state_id": 19},
        {"id": 382, "name": "Gwarzo", "state_id": 19},
        {"id": 383, "name": "Kabo", "state_id": 19},
        {"id": 384, "name": "Kano Municipal", "state_id": 19},
        {"id": 385, "name": "Karaye", "state_id": 19},
        {"id": 386, "name": "Kibiya", "state_id": 19},
        {"id": 387, "name": "Kiru", "state_id": 19},
        {"id": 388, "name": "Kumbotso", "state_id": 19},
        {"id": 389, "name": "Kunchi", "state_id": 19},
        {"id": 390, "name": "Kura", "state_id": 19},
        {"id": 391, "name": "Madobi", "state_id": 19},
        {"id": 392, "name": "Makoda", "state_id": 19},
        {"id": 393, "name": "Minjibir", "state_id": 19},
        {"id": 394, "name": "Nasarawa", "state_id": 19},
        {"id": 395, "name": "Rano", "state_id": 19},
        {"id": 396, "name": "Rimin Gado", "state_id": 19},
        {"id": 397, "name": "Rogo", "state_id": 19},
        {"id": 398, "name": "Shanono", "state_id": 19},
        {"id": 399, "name": "Sumaila", "state_id": 19},
        {"id": 400, "name": "Takai", "state_id": 19},
        {"id": 401, "name": "Tarauni", "state_id": 19},
        {"id": 402, "name": "Tofa", "state_id": 19},
        {"id": 403, "name": "Tsanyawa", "state_id": 19},
        {"id": 404, "name": "Tudun Wada", "state_id": 19},
        {"id": 405, "name": "Ungogo", "state_id": 19},
        {"id": 406, "name": "Warawa", "state_id": 19},
        {"id": 407, "name": "Wudil", "state_id": 19},
        # LGAs for Katsina State
        {"id": 408, "name": "Bakori", "state_id": 20},
        {"id": 409, "name": "Batagarawa", "state_id": 20},
        {"id": 410, "name": "Batsari", "state_id": 20},
        {"id": 411, "name": "Baure", "state_id": 20},
        {"id": 412, "name": "Bindawa", "state_id": 20},
        {"id": 413, "name": "Charanchi", "state_id": 20},
        {"id": 414, "name": "Dan Musa", "state_id": 20},
        {"id": 415, "name": "Dandume", "state_id": 20},
        {"id": 416, "name": "Danja", "state_id": 20},
        {"id": 417, "name": "Daura", "state_id": 20},
        {"id": 418, "name": "Dutsi", "state_id": 20},
        {"id": 419, "name": "Dutsin-Ma", "state_id": 20},
        {"id": 420, "name": "Faskari", "state_id": 20},
        {"id": 421, "name": "Funtua", "state_id": 20},
        {"id": 422, "name": "Ingawa", "state_id": 20},
        {"id": 423, "name": "Jibia", "state_id": 20},
        {"id": 424, "name": "Kafur", "state_id": 20},
        {"id": 425, "name": "Kaita", "state_id": 20},
        {"id": 426, "name": "Kankara", "state_id": 20},
        {"id": 427, "name": "Kankia", "state_id": 20},
        {"id": 428, "name": "Katsina", "state_id": 20},
        {"id": 429, "name": "Kurfi", "state_id": 20},
        {"id": 430, "name": "Kusada", "state_id": 20},
        {"id": 431, "name": "Mai'Adua", "state_id": 20},
        {"id": 432, "name": "Malumfashi", "state_id": 20},
        {"id": 433, "name": "Mani", "state_id": 20},
        {"id": 434, "name": "Mashi", "state_id": 20},
        {"id": 435, "name": "Matazu", "state_id": 20},
        {"id": 436, "name": "Musawa", "state_id": 20},
        {"id": 437, "name": "Rimi", "state_id": 20},
        {"id": 438, "name": "Sabuwa", "state_id": 20},
        {"id": 439, "name": "Safana", "state_id": 20},
        {"id": 440, "name": "Sandamu", "state_id": 20},
        {"id": 441, "name": "Zango", "state_id": 20},
        # LGAs for Kebbi State
        {"id": 442, "name": "Aleiro", "state_id": 21},
        {"id": 443, "name": "Arewa Dandi", "state_id": 21},
        {"id": 444, "name": "Argungu", "state_id": 21},
        {"id": 445, "name": "Augie", "state_id": 21},
        {"id": 446, "name": "Bagudo", "state_id": 21},
        {"id": 447, "name": "Birnin Kebbi", "state_id": 21},
        {"id": 448, "name": "Bunza", "state_id": 21},
        {"id": 449, "name": "Dandi", "state_id": 21},
        {"id": 450, "name": "Fakai", "state_id": 21},
        {"id": 451, "name": "Gwandu", "state_id": 21},
        {"id": 452, "name": "Jega", "state_id": 21},
        {"id": 453, "name": "Kalgo", "state_id": 21},
        {"id": 454, "name": "Koko/Besse", "state_id": 21},
        {"id": 455, "name": "Maiyama", "state_id": 21},
        {"id": 456, "name": "Ngaski", "state_id": 21},
        {"id": 457, "name": "Sakaba", "state_id": 21},
        {"id": 458, "name": "Shanga", "state_id": 21},
        {"id": 459, "name": "Suru", "state_id": 21},
        {"id": 460, "name": "Wasagu/Danko", "state_id": 21},
        {"id": 461, "name": "Yauri", "state_id": 21},
        {"id": 462, "name": "Zuru", "state_id": 21},
        # LGAs for Kogi State
        {"id": 463, "name": "Adavi", "state_id": 22},
        {"id": 464, "name": "Ajaokuta", "state_id": 22},
        {"id": 465, "name": "Ankpa", "state_id": 22},
        {"id": 466, "name": "Bassa", "state_id": 22},
        {"id": 467, "name": "Dekina", "state_id": 22},
        {"id": 468, "name": "Ibaji", "state_id": 22},
        {"id": 469, "name": "Idah", "state_id": 22},
        {"id": 470, "name": "Igalamela Odolu", "state_id": 22},
        {"id": 471, "name": "Ijumu", "state_id": 22},
        {"id": 472, "name": "Kabba/Bunu", "state_id": 22},
        {"id": 473, "name": "Kogi", "state_id": 22},
        {"id": 474, "name": "Lokoja", "state_id": 22},
        {"id": 475, "name": "Mopa Muro", "state_id": 22},
        {"id": 476, "name": "Ofu", "state_id": 22},
        {"id": 477, "name": "Ogori/Magongo", "state_id": 22},
        {"id": 478, "name": "Okehi", "state_id": 22},
        {"id": 479, "name": "Okene", "state_id": 22},
        {"id": 480, "name": "Olamaboro", "state_id": 22},
        {"id": 481, "name": "Omala", "state_id": 22},
        {"id": 482, "name": "Yagba East", "state_id": 22},
        {"id": 483, "name": "Yagba West", "state_id": 22},
        # LGAs for Kwara State
        {"id": 484, "name": "Asa", "state_id": 23},
        {"id": 485, "name": "Baruten", "state_id": 23},
        {"id": 486, "name": "Edu", "state_id": 23},
        {"id": 487, "name": "Ekiti", "state_id": 23},
        {"id": 488, "name": "Ifelodun", "state_id": 23},
        {"id": 489, "name": "Ilorin East", "state_id": 23},
        {"id": 490, "name": "Ilorin South", "state_id": 23},
        {"id": 491, "name": "Ilorin West", "state_id": 23},
        {"id": 492, "name": "Irepodun", "state_id": 23},
        {"id": 493, "name": "Isin", "state_id": 23},
        {"id": 494, "name": "Kaiama", "state_id": 23},
        {"id": 495, "name": "Moro", "state_id": 23},
        {"id": 496, "name": "Offa", "state_id": 23},
        {"id": 497, "name": "Oke Ero", "state_id": 23},
        {"id": 498, "name": "Oyun", "state_id": 23},
        {"id": 499, "name": "Pategi", "state_id": 23},
        # LGAs for Lagos State
        {"id": 500, "name": "Agege", "state_id": 24},
        {"id": 501, "name": "Ajeromi-Ifelodun", "state_id": 24},
        {"id": 502, "name": "Alimosho", "state_id": 24},
        {"id": 503, "name": "Amuwo-Odofin", "state_id": 24},
        {"id": 504, "name": "Apapa", "state_id": 24},
        {"id": 505, "name": "Badagry", "state_id": 24},
        {"id": 506, "name": "Epe", "state_id": 24},
        {"id": 507, "name": "Eti-Osa", "state_id": 24},
        {"id": 508, "name": "Ibeju-Lekki", "state_id": 24},
        {"id": 509, "name": "Ifako-Ijaiye", "state_id": 24},
        {"id": 510, "name": "Ikeja", "state_id": 24},
        {"id": 511, "name": "Ikorodu", "state_id": 24},
        {"id": 512, "name": "Kosofe", "state_id": 24},
        {"id": 513, "name": "Lagos Island", "state_id": 24},
        {"id": 514, "name": "Lagos Mainland", "state_id": 24},
        {"id": 515, "name": "Mushin", "state_id": 24},
        {"id": 516, "name": "Ojo", "state_id": 24},
        {"id": 517, "name": "Oshodi-Isolo", "state_id": 24},
        {"id": 518, "name": "Shomolu", "state_id": 24},
        {"id": 519, "name": "Surulere", "state_id": 24},
        # LGAs for Nasarawa State
        {"id": 520, "name": "Awe", "state_id": 25},
        {"id": 521, "name": "Doma", "state_id": 25},
        {"id": 522, "name": "Karu", "state_id": 25},
        {"id": 523, "name": "Keana", "state_id": 25},
        {"id": 524, "name": "Keffi", "state_id": 25},
        {"id": 525, "name": "Kokona", "state_id": 25},
        {"id": 526, "name": "Lafia", "state_id": 25},
        {"id": 527, "name": "Nasarawa", "state_id": 25},
        {"id": 528, "name": "Nasarawa Egon", "state_id": 25},
        {"id": 529, "name": "Obi", "state_id": 25},
        {"id": 530, "name": "Toto", "state_id": 25},
        {"id": 531, "name": "Wamba", "state_id": 25},
        # LGAs for Niger State
        {"id": 532, "name": "Agaie", "state_id": 26},
        {"id": 533, "name": "Agwara", "state_id": 26},
        {"id": 534, "name": "Bida", "state_id": 26},
        {"id": 535, "name": "Borgu", "state_id": 26},
        {"id": 536, "name": "Bosso", "state_id": 26},
        {"id": 537, "name": "Chanchaga", "state_id": 26},
        {"id": 538, "name": "Edati", "state_id": 26},
        {"id": 539, "name": "Gbako", "state_id": 26},
        {"id": 540, "name": "Gurara", "state_id": 26},
        {"id": 541, "name": "Katcha", "state_id": 26},
        {"id": 542, "name": "Kontagora", "state_id": 26},
        {"id": 543, "name": "Lapai", "state_id": 26},
        {"id": 544, "name": "Lavun", "state_id": 26},
        {"id": 545, "name": "Magama", "state_id": 26},
        {"id": 546, "name": "Mariga", "state_id": 26},
        {"id": 547, "name": "Mashegu", "state_id": 26},
        {"id": 548, "name": "Mokwa", "state_id": 26},
        {"id": 549, "name": "Munya", "state_id": 26},
        {"id": 550, "name": "Paikoro", "state_id": 26},
        {"id": 551, "name": "Rafi", "state_id": 26},
        {"id": 552, "name": "Rijau", "state_id": 26},
        {"id": 553, "name": "Shiroro", "state_id": 26},
        {"id": 554, "name": "Suleja", "state_id": 26},
        {"id": 555, "name": "Tafa", "state_id": 26},
        {"id": 556, "name": "Wushishi", "state_id": 26},
        # LGAs for Ogun State
        {"id": 557, "name": "Abeokuta North", "state_id": 27},
        {"id": 558, "name": "Abeokuta South", "state_id": 27},
        {"id": 559, "name": "Ado-Odo/Ota", "state_id": 27},
        {"id": 560, "name": "Egbado North", "state_id": 27},
        {"id": 561, "name": "Egbado South", "state_id": 27},
        {"id": 562, "name": "Ewekoro", "state_id": 27},
        {"id": 563, "name": "Ifo", "state_id": 27},
        {"id": 564, "name": "Ijebu East", "state_id": 27},
        {"id": 565, "name": "Ijebu North", "state_id": 27},
        {"id": 566, "name": "Ijebu North East", "state_id": 27},
        {"id": 567, "name": "Ijebu Ode", "state_id": 27},
        {"id": 568, "name": "Ikenne", "state_id": 27},
        {"id": 569, "name": "Imeko Afon", "state_id": 27},
        {"id": 570, "name": "Ipokia", "state_id": 27},
        {"id": 571, "name": "Obafemi Owode", "state_id": 27},
        {"id": 572, "name": "Odeda", "state_id": 27},
        {"id": 573, "name": "Odogbolu", "state_id": 27},
        {"id": 574, "name": "Ogun Waterside", "state_id": 27},
        {"id": 575, "name": "Remo North", "state_id": 27},
        {"id": 576, "name": "Sagamu", "state_id": 27},
        {"id": 577, "name": "Yewa North", "state_id": 27},
        {"id": 578, "name": "Yewa South", "state_id": 27},
        # LGAs for Ondo State
        {"id": 579, "name": "Akoko North-East", "state_id": 28},
        {"id": 580, "name": "Akoko North-West", "state_id": 28},
        {"id": 581, "name": "Akoko South-East", "state_id": 28},
        {"id": 582, "name": "Akoko South-West", "state_id": 28},
        {"id": 583, "name": "Akure North", "state_id": 28},
        {"id": 584, "name": "Akure South", "state_id": 28},
        {"id": 585, "name": "Ese Odo", "state_id": 28},
        {"id": 586, "name": "Idanre", "state_id": 28},
        {"id": 587, "name": "Ifedore", "state_id": 28},
        {"id": 588, "name": "Ilaje", "state_id": 28},
        {"id": 589, "name": "Ile Oluji/Okeigbo", "state_id": 28},
        {"id": 590, "name": "Irele", "state_id": 28},
        {"id": 591, "name": "Odigbo", "state_id": 28},
        {"id": 592, "name": "Okitipupa", "state_id": 28},
        {"id": 593, "name": "Ondo East", "state_id": 28},
        {"id": 594, "name": "Ondo West", "state_id": 28},
        {"id": 595, "name": "Ose", "state_id": 28},
        {"id": 596, "name": "Owo", "state_id": 28},
        # LGAs for Osun State
        {"id": 597, "name": "Atakunmosa East", "state_id": 29},
        {"id": 598, "name": "Atakunmosa West", "state_id": 29},
        {"id": 599, "name": "Aiyedaade", "state_id": 29},
        {"id": 600, "name": "Aiyedire", "state_id": 29},
        {"id": 601, "name": "Boluwaduro", "state_id": 29},
        {"id": 602, "name": "Boripe", "state_id": 29},
        {"id": 603, "name": "Ede North", "state_id": 29},
        {"id": 604, "name": "Ede South", "state_id": 29},
        {"id": 605, "name": "Ife Central", "state_id": 29},
        {"id": 606, "name": "Ife East", "state_id": 29},
        {"id": 607, "name": "Ife North", "state_id": 29},
        {"id": 608, "name": "Ife South", "state_id": 29},
        {"id": 609, "name": "Egbedore", "state_id": 29},
        {"id": 610, "name": "Ejigbo", "state_id": 29},
        {"id": 611, "name": "Ifedayo", "state_id": 29},
        {"id": 612, "name": "Ifelodun", "state_id": 29},
        {"id": 613, "name": "Ila", "state_id": 29},
        {"id": 614, "name": "Ilesa East", "state_id": 29},
        {"id": 615, "name": "Ilesa West", "state_id": 29},
        {"id": 616, "name": "Irepodun", "state_id": 29},
        {"id": 617, "name": "Irewole", "state_id": 29},
        {"id": 618, "name": "Isokan", "state_id": 29},
        {"id": 619, "name": "Iwo", "state_id": 29},
        {"id": 620, "name": "Obokun", "state_id": 29},
        {"id": 621, "name": "Odo Otin", "state_id": 29},
        {"id": 622, "name": "Ola Oluwa", "state_id": 29},
        {"id": 623, "name": "Olorunda", "state_id": 29},
        {"id": 624, "name": "Oriade", "state_id": 29},
        {"id": 625, "name": "Orolu", "state_id": 29},
        {"id": 626, "name": "Osogbo", "state_id": 29},
        # LGAs for Oyo State
        {"id": 627, "name": "Afijio", "state_id": 30},
        {"id": 628, "name": "Akinyele", "state_id": 30},
        {"id": 629, "name": "Atiba", "state_id": 30},
        {"id": 630, "name": "Atisbo", "state_id": 30},
        {"id": 631, "name": "Egbeda", "state_id": 30},
        {"id": 632, "name": "Ibadan North", "state_id": 30},
        {"id": 633, "name": "Ibadan North-East", "state_id": 30},
        {"id": 634, "name": "Ibadan North-West", "state_id": 30},
        {"id": 635, "name": "Ibadan South-East", "state_id": 30},
        {"id": 636, "name": "Ibadan South-West", "state_id": 30},
        {"id": 637, "name": "Ibarapa Central", "state_id": 30},
        {"id": 638, "name": "Ibarapa East", "state_id": 30},
        {"id": 639, "name": "Ibarapa North", "state_id": 30},
        {"id": 640, "name": "Ido", "state_id": 30},
        {"id": 641, "name": "Irepo", "state_id": 30},
        {"id": 642, "name": "Iseyin", "state_id": 30},
        {"id": 643, "name": "Itesiwaju", "state_id": 30},
        {"id": 644, "name": "Iwajowa", "state_id": 30},
        {"id": 645, "name": "Kajola", "state_id": 30},
        {"id": 646, "name": "Lagelu", "state_id": 30},
        {"id": 647, "name": "Ogbomosho North", "state_id": 30},
        {"id": 648, "name": "Ogbomosho South", "state_id": 30},
        {"id": 649, "name": "Ogo Oluwa", "state_id": 30},
        {"id": 650, "name": "Olorunsogo", "state_id": 30},
        {"id": 651, "name": "Oluyole", "state_id": 30},
        {"id": 652, "name": "Ona Ara", "state_id": 30},
        {"id": 653, "name": "Orelope", "state_id": 30},
        {"id": 654, "name": "Ori Ire", "state_id": 30},
        {"id": 655, "name": "Oyo", "state_id": 30},
        {"id": 656, "name": "Oyo East", "state_id": 30},
        {"id": 657, "name": "Saki East", "state_id": 30},
        {"id": 658, "name": "Saki West", "state_id": 30},
        {"id": 659, "name": "Surulere", "state_id": 30},
        # LGAs for Plateau State
        {"id": 660, "name": "Barkin Ladi", "state_id": 31},
        {"id": 661, "name": "Bassa", "state_id": 31},
        {"id": 662, "name": "Bokkos", "state_id": 31},
        {"id": 663, "name": "Jos East", "state_id": 31},
        {"id": 664, "name": "Jos North", "state_id": 31},
        {"id": 665, "name": "Jos South", "state_id": 31},
        {"id": 666, "name": "Kanam", "state_id": 31},
        {"id": 667, "name": "Kanke", "state_id": 31},
        {"id": 668, "name": "Langtang North", "state_id": 31},
        {"id": 669, "name": "Langtang South", "state_id": 31},
        {"id": 670, "name": "Mangu", "state_id": 31},
        {"id": 671, "name": "Mikang", "state_id": 31},
        {"id": 672, "name": "Pankshin", "state_id": 31},
        {"id": 673, "name": "Qua'an Pan", "state_id": 31},
        {"id": 674, "name": "Riyom", "state_id": 31},
        {"id": 675, "name": "Shendam", "state_id": 31},
        {"id": 676, "name": "Wase", "state_id": 31},
        # LGAs for Rivers State
        {"id": 677, "name": "Abua/Odual", "state_id": 32},
        {"id": 678, "name": "Ahoada East", "state_id": 32},
        {"id": 679, "name": "Ahoada West", "state_id": 32},
        {"id": 680, "name": "Akuku-Toru", "state_id": 32},
        {"id": 681, "name": "Andoni", "state_id": 32},
        {"id": 682, "name": "Asari-Toru", "state_id": 32},
        {"id": 683, "name": "Bonny", "state_id": 32},
        {"id": 684, "name": "Degema", "state_id": 32},
        {"id": 685, "name": "Eleme", "state_id": 32},
        {"id": 686, "name": "Emuoha", "state_id": 32},
        {"id": 687, "name": "Etche", "state_id": 32},
        {"id": 688, "name": "Gokana", "state_id": 32},
        {"id": 689, "name": "Ikwerre", "state_id": 32},
        {"id": 690, "name": "Khana", "state_id": 32},
        {"id": 691, "name": "Obio/Akpor", "state_id": 32},
        {"id": 692, "name": "Ogba/Egbema/Ndoni", "state_id": 32},
        {"id": 693, "name": "Ogu/Bolo", "state_id": 32},
        {"id": 694, "name": "Okrika", "state_id": 32},
        {"id": 695, "name": "Omuma", "state_id": 32},
        {"id": 696, "name": "Opobo/Nkoro", "state_id": 32},
        {"id": 697, "name": "Oyigbo", "state_id": 32},
        {"id": 698, "name": "Port Harcourt", "state_id": 32},
        {"id": 699, "name": "Tai", "state_id": 32},
        # LGAs for Sokoto State
        {"id": 700, "name": "Binji", "state_id": 33},
        {"id": 701, "name": "Bodinga", "state_id": 33},
        {"id": 702, "name": "Dange Shuni", "state_id": 33},
        {"id": 703, "name": "Gada", "state_id": 33},
        {"id": 704, "name": "Goronyo", "state_id": 33},
        {"id": 705, "name": "Gudu", "state_id": 33},
        {"id": 706, "name": "Gwadabawa", "state_id": 33},
        {"id": 707, "name": "Illela", "state_id": 33},
        {"id": 708, "name": "Isa", "state_id": 33},
        {"id": 709, "name": "Kebbe", "state_id": 33},
        {"id": 710, "name": "Kware", "state_id": 33},
        {"id": 711, "name": "Rabah", "state_id": 33},
        {"id": 712, "name": "Sabon Birni", "state_id": 33},
        {"id": 713, "name": "Shagari", "state_id": 33},
        {"id": 714, "name": "Silame", "state_id": 33},
        {"id": 715, "name": "Sokoto North", "state_id": 33},
        {"id": 716, "name": "Sokoto South", "state_id": 33},
        {"id": 717, "name": "Tambuwal", "state_id": 33},
        {"id": 718, "name": "Tangaza", "state_id": 33},
        {"id": 719, "name": "Tureta", "state_id": 33},
        {"id": 720, "name": "Wamako", "state_id": 33},
        {"id": 721, "name": "Wurno", "state_id": 33},
        {"id": 722, "name": "Yabo", "state_id": 33},
        # LGAs for Taraba State
        {"id": 723, "name": "Ardo Kola", "state_id": 34},
        {"id": 724, "name": "Bali", "state_id": 34},
        {"id": 725, "name": "Donga", "state_id": 34},
        {"id": 726, "name": "Gashaka", "state_id": 34},
        {"id": 727, "name": "Gassol", "state_id": 34},
        {"id": 728, "name": "Ibi", "state_id": 34},
        {"id": 729, "name": "Jalingo", "state_id": 34},
        {"id": 730, "name": "Karim Lamido", "state_id": 34},
        {"id": 731, "name": "Kumi", "state_id": 34},
        {"id": 732, "name": "Lau", "state_id": 34},
        {"id": 733, "name": "Sardauna", "state_id": 34},
        {"id": 734, "name": "Takum", "state_id": 34},
        {"id": 735, "name": "Ussa", "state_id": 34},
        {"id": 736, "name": "Wukari", "state_id": 34},
        {"id": 737, "name": "Yorro", "state_id": 34},
        {"id": 738, "name": "Zing", "state_id": 34},
        # LGAs for Yobe State
        {"id": 739, "name": "Bade", "state_id": 35},
        {"id": 740, "name": "Bursari", "state_id": 35},
        {"id": 741, "name": "Damaturu", "state_id": 35},
        {"id": 742, "name": "Fika", "state_id": 35},
        {"id": 743, "name": "Fune", "state_id": 35},
        {"id": 744, "name": "Geidam", "state_id": 35},
        {"id": 745, "name": "Gujba", "state_id": 35},
        {"id": 746, "name": "Gulani", "state_id": 35},
        {"id": 747, "name": "Jakusko", "state_id": 35},
        {"id": 748, "name": "Karasuwa", "state_id": 35},
        {"id": 749, "name": "Machina", "state_id": 35},
        {"id": 750, "name": "Nangere", "state_id": 35},
        {"id": 751, "name": "Nguru", "state_id": 35},
        {"id": 752, "name": "Potiskum", "state_id": 35},
        {"id": 753, "name": "Tarmuwa", "state_id": 35},
        {"id": 754, "name": "Yunusari", "state_id": 35},
        {"id": 755, "name": "Yusufari", "state_id": 35},
        # LGAs for Zamfara State
        {"id": 756, "name": "Anka", "state_id": 36},
        {"id": 757, "name": "Bakura", "state_id": 36},
        {"id": 758, "name": "Birnin Magaji/Kiyaw", "state_id": 36},
        {"id": 759, "name": "Bukkuyum", "state_id": 36},
        {"id": 760, "name": "Bungudu", "state_id": 36},
        {"id": 761, "name": "Gummi", "state_id": 36},
        {"id": 762, "name": "Gusau", "state_id": 36},
        {"id": 763, "name": "Kaura Namoda", "state_id": 36},
        {"id": 764, "name": "Maradun", "state_id": 36},
        {"id": 765, "name": "Maru", "state_id": 36},
        {"id": 766, "name": "Shinkafi", "state_id": 36},
        {"id": 767, "name": "Talata Mafara", "state_id": 36},
        {"id": 768, "name": "Chafe", "state_id": 36},
        {"id": 769, "name": "Zurmi", "state_id": 36},
        # LGAs for FCT Abuja
        {"id": 770, "name": "Abaji", "state_id": 37},
        {"id": 771, "name": "Bwari", "state_id": 37},
        {"id": 772, "name": "Gwagwalada", "state_id": 37},
        {"id": 773, "name": "Kuje", "state_id": 37},
        {"id": 774, "name": "Kwali", "state_id": 37},
        {"id": 775, "name": "Municipal Area Council", "state_id": 37}
    ]
}